version: '3.8'
services:
  frontend:
    image: frontend-vue
    env_file:
      - .env
    build:
      context: Frontend
      dockerfile: Dockerfile  
    ports:
      - '8080:8080'


  backend:
    image: backend-py
    hostname: python
    build:
      context: Backend
      dockerfile: Dockerfile
    env_file:
    - .env
    
    ports:
      - '7003:7003'

  db:
    image: postgres:14.7-alpine
    hostname: db
    restart: always
    env_file:
    - .env

    volumes: 
      - db:/var/lib/postgresql/data

    
  redis:
    image: docker.io/bitnami/redis:7.0
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  db:
    driver: local
  redis_data:
    driver: local
 
